### ISSUE TITLE
luaharfbuzz no longer compatible with Lua 5.2

### ISSUE THREAD

**Issue by deepakjois** [ufyTeX/luaharfbuzz#52]
I turned on automated testing via Github Actions and realized that luaharfbuzz is no longer compatible with Lua 5.2. This is due to the introduction of the `lua_geti` Lua C API function in a few places. `lua_geti` is available only in Lua 5.3 and above.

I am inclined to just drop compatibility for Lua 5.2. LuaTeX, which is probably the only main consumer of this package is already at Lua 5.3.

@zauguin What do you think? If you agree, I will make the changes to the rockspec file and remove Lua 5.2 from the testing matrix.

**Comment by zauguin** [comment]
Since Lua reached 5.4 by now and LuaTeX is also at 5.3, I agree that dropping 5.2 compatibility makes sense. The only reason I can think of for keeping older compatibility would be LuaJITTeX, but LuaJITTeX never got 5.2 in the first place.

**Comment by deepakjois** [comment]
Done in 4ee63481f1cf68cb163f0eced51f5f4335b92090 and bd1d12ce497224fbe8e02c0e5574fd53052526e5
